spring:
  application:
    name: timetracker-backend

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    locations: classpath:db/migration

  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

  web:
    cors:
      allowed-origins: "http://localhost:3000,http://localhost:3001"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false

logging:
  level:
    com.timetracker: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

app:
  version: "1.0.0"
  name: "Time Tracker"
  mode: "local" # local or hosted

# Default values - override in profile-specific files
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always