spring:
  web:
    cors:
      allowed-origins: "**, http://localhost:3000"
  datasource:
    url: jdbc:postgresql://localhost:5433/timetracker  # Changed from 5432 to 5433
    username: timetracker
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      leak-detection-threshold: 60000

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    clean-disabled: false
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    com.timetracker: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.flywaydb: DEBUG

server:
  port: 8080

app:
  mode: "local"